logging.level.net.samplelogin: debug

spring:
    thymeleaf.mode: LEGACYHTML5
    social:
        auto_connection_views: true
        facebook:
            appId: ???
            appSecret: ???
        twitter:
            appId: ???
            appSecret: ???
        linkedin:
            appId: ???
            appSecret: ???
        google:
            appId: ???
            appSecret: ???
    datasource:
        url: jdbc:h2:mem:sample_login
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate.ddl-auto: none
        database-platform: org.hibernate.dialect.H2Dialect

security.require_ssl: true

recaptcha.data:
    sitekey: ???
    secret: ???

