logging.level.net.samplelogin: debug

spring:
    thymeleaf.mode: LEGACYHTML5
    social:
        auto_connection_views: true
        facebook:
            appId: 402926243408451
            appSecret: 08fd034a45d214e522e1a43f799d980b
        twitter:
            appId: c5DR7jVKwvgdBE7uxSF2SZONs
            appSecret: Z3TRfr7URzyimHiKYAjnwOBnz20AXq6anzLSMYFtFSDPTROlvf
        linkedin:
            appId: 78g1cfq6ewnbju
            appSecret: qQgqclTNx7kkPu0R
        google:
            appId: 366063999039-3s0m207ao69okpuctn2qli66kred3s2o.apps.googleusercontent.com
            appSecret: DxkZQbUhXw0TL7NPxkKIj3sy
    datasource:
        url: jdbc:h2:mem:sample_login
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate.ddl-auto: none
        database-platform: org.hibernate.dialect.H2Dialect
