CREATE TABLE app_user (
  app_user_id INTEGER AUTO_INCREMENT,
  email VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  confirmed BOOLEAN NOT NULL DEFAULT false,
);